### ISSUE TITLE
Support for macOS 10.15 (Catalina)

### ISSUE THREAD

**Issue by eculturedk** [msintuneappsdk/intune-app-wrapping-tool-mac#17]
When running the current IntuneAppUtil on macOS 10.15 Beta 1 (Catalina), it says:

zsh: bad CPU type in executable: ./IntuneAppUtil

Probably due to 32-bit app? macOS 10.15 only runs 64-bit apps.

**Comment by arnabbiswas** [comment]
This is fixed in today's update.

**Comment by svenwiegand** [comment]
@arnabbiswas For me this problem does still occur on Catalina 10.15.6 with latest version and 1.2.

**Comment by svenwiegand** [comment]
I need to correct myself. Applying execution permission to `IntuneAppUtil` and calling it with `./IntuneAppUtil` works.
